Update code for version 1.2 of metadata schema
sensiblecodeio/csv-to-cantabular-metadata-2021 pull request #21
Opened 2022-07-06 07:39 UTC by phynes-sensiblecode

2022-07-14 21:30 UTC, phynes-sensiblecode commented on test/test_integration.py
> +                             f'Comparing out/{FILENAME_TABLES} and expected/dataset-metadata.json')
Should be `expected/table-metadata.json`

2022-07-14 23:04 UTC, SpencerHedger requested changes
Looks good, my comment on observation types has been discussed already so that leaves just the error you subsequently spotted and commented on (https://github.com/sensiblecodeio/csv-to-cantabular-metadata-2021/pull/21#discussion_r921587046) to be fixed.

2022-07-14 23:04 UTC, SpencerHedger commented on ctb_metadata_files/metadata.graphql
> +type Observation_Type {
Discussed with @phynes-sensiblecode and this is something that can be changed later when the aforementioned PR is completed.

2022-07-15 08:39 UTC, SpencerHedger approved these changes
Looks good.

2022-07-15 08:40 UTC, merged