Formatted filenames
sensiblecodeio/csv-to-cantabular-metadata-2021 pull request #8
Opened 2022-04-28 14:54 UTC by phynes-sensiblecode

Output files with requested name format.

2022-05-08 22:00 UTC, SpencerHedger requested changes
Just two issues that I could find.

2022-05-09 10:10 UTC, phynes-sensiblecode commented on bin/ons_csv_to_ctb_json_main.py
> +    base_filename = output_filename(args.file_prefix, args.metadata_master_version,
I'll validate that all characters are either alphanumeric or one of `"-"`, `"_"`, `"."`, `" "`

2022-05-09 10:10 UTC, phynes-sensiblecode commented on bin/ons_csv_to_ctb_json_main.py
> +                                    args.build_number)
I'll check for numbers greater than or equal to 0

2022-05-09 11:13 UTC, SpencerHedger approved these changes
Looks good.

2022-05-09 11:28 UTC, merged